apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: kuberay-eks

profiles:
  # Profile for setting up the Kuberay Operator for managing Ray clusters/jobs/services
  - name: operator

    deploy:
      helm:
        releases:
          - name: kuberay-operator
            repo: https://ray-project.github.io/kuberay-helm/
            remoteChart: kuberay-operator
            version: 1.0.0
            namespace: kuberay
            createNamespace: true
            upgradeOnChange: true

  # Profile for running a Ray Cluster
  - name: cluster

    deploy:
      helm:
        releases:
          - name: raycluster
            repo: https://ray-project.github.io/kuberay-helm/
            remoteChart: ray-cluster
            version: 1.0.0
            namespace: kuberay
            createNamespace: true
            setValues:
              image.repository: rayproject/ray
              # Use -aarch64 image tag when running on Apple Silicon (M1/M2)
              image.tag: 2.9.0-py39-aarch64
              #image.tag: 2.9.0
              head.rayVersion: 2.9.0
              head.resources.limits.cpu: 2
              head.resources.limits.memory: 8G
              head.resources.requests.cpu: 2
              head.resources.requests.memory: 8G
              worker.replicas: 2
              worker.resources.limits.cpu: 2
              worker.resources.limits.memory: 8G
              worker.resources.requests.cpu: 2
              worker.resources.requests.memory: 8G
            upgradeOnChange: true

  # Profile for deploying models on Ray Serve
  - name: serve

    deploy:
      kubectl:
        manifests:
          #- apps/ray_v1alpha1_rayservice.yaml
          - apps/mobilenet/ray-service.mobilenet.yaml